version: 2
jobs:
  build:
    docker:
      - image: ishikocpp/gcc-boost:10.1.0-1.73.0
    steps:
      - run:
          name: "Set ISHIKO_CPP environment variable and create workspace directory"
          command: mkdir -p /projects/ishiko/cpp && echo 'export ISHIKO_CPP="/projects/ishiko/cpp"' >> $BASH_ENV
      - run:
          name: "Install build dependency: Ishiko/C++ Collections"
          command: cd /projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/collections.git && cd collections/build/gnumake && make
      - checkout:
          path: /projects/ishiko/cpp/tasks
      - run:
          name: Build
          command: cd /projects/ishiko/cpp/tasks/Makefiles/GNUmakefile && make
      - run:
          name: "Install test dependency: Ishiko/C++ Platform"
          command: cd /projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/platform.git && cd platform/build/gnumake && make
      - run:
          name: "Install test dependency: Ishiko/C++ Errors"
          command: cd /projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/errors.git && cd errors/build/gnumake && make
      - run:
          name: "Install test dependency: Ishiko/C++ Process"
          command: cd /projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/process.git && cd process/build/gnumake && make
      - run:
          name: "Checkout Ishiko-cpp/TestFramework test dependency"
          command: cd /Ishiko-cpp && git clone https://github.com/Ishiko-cpp/TestFramework.git
      - run:
          name: "Build Ishiko-cpp/TestFramework test dependency"
          command: cd /Ishiko-cpp/TestFramework/Core/Makefiles/GNUmakefile && make
      - run:
          name: Test build
          command: cd /Ishiko-cpp/Tasks/Tests/Makefiles/GNUmakefile && make
      - run:
          name: Run the tests
          command: cd /Ishiko-cpp/Tasks/Tests/Makefiles/GNUmakefile && ./IshikoTasksTests
